name: build_product

on:
  push:
    branches:
      - "tolstikov/dev"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
        - 
          name: Checkout
          uses: actions/checkout@v1
          with:
            ref: 'tolstikov/dev'
        - 
          name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        - 
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - 
          name: Build and push image
          uses: docker/build-push-action@v3
          with:
            context: .
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/devops:latest
